apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
   app: webapp
spec:
  volumes:
    - name: app
      emptyDir: {}
  containers:
  - name: otus-hw1
    image: uwscsi/otus-hw1:otus-hw1
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-index
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app